production:
  bucket: data-engineering
  access_key_id: AKIAIQPLQCDIVSVGIQDQ
  secret_access_key: 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
development:
  bucket: data-engineering-dev
  access_key_id: AKIAIQPLQCDIVSVGIQDQ
  secret_access_key: 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
test:
  bucket: data-engineering-test
  access_key_id: AKIAIQPLQCDIVSVGIQDQ
  secret_access_key: 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
